services:
  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - ./config:/config
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
      - /dev:/dev
    devices:
      - /dev/serial/by-id/usb-ITead_Sonoff_Zigbee_3.0_USB_Dongle_Plus_46ed5bdff71bef1181029cd94909ffd0-if00-port0
    restart: unless-stopped
    ports:
      - 127.0.0.1:8123:8123
      - ${LAN_IP}:8123:8123
    environment:
      - TZ=America/Los_Angeles
  zwave:
    container_name: zwave
    image: zwavejs/zwave-js-ui:9.27.8
    restart: unless-stopped
    devices:
      - /dev/serial/by-id/usb-Zooz_800_Z-Wave_Stick_533D004242-if00:/dev/zwave
    volumes:
      - zwave-config:/usr/src/app/store
    environment:
      - ZWAVEJS_EXTERNAL_CONFIG=/usr/src/app/store/.config-db
    ports:
      - 127.0.0.1:8091:8091
      - ${LAN_IP}:8091:8091
  cloudflared:
    container_name: cloudflared
    image: cloudflare/cloudflared:2024.12.1
    command: tunnel run homeassistant-tunnel
    volumes:
      - ${CLOUDFLARED_PATH}/cert.pem:/etc/cloudflared/cert.pem:ro
      - ${CLOUDFLARED_PATH}/config.yml:/etc/cloudflared/config.yml:ro
      - ${CLOUDFLARED_PATH}/${CLOUDFLARED_TUNNEL_ID}.json:/etc/cloudflared/${CLOUDFLARED_TUNNEL_ID}.json:ro
    restart: unless-stopped
volumes:
  zwave-config:

